config/routes.rb
Rails.application.routes.draw do
  devise_for :members, :controllers => { registrations: 'registrations'}
  resources :posts, only: [:new, :create, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_member!, except: %i[index show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order('created_at DESC')
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = current_member.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:member).permit(:username, :email, :password, :password_confimation)
  end

  def account_update_params
    params.require(:member).permit(:username, :email, :password, :password_confimation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MembersOnly</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-gray">
  <% if flash[:notice] %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <p class="notice"><%= notice %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <p class="alert"><%= alert %></p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>

  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to "Members Only", root_path, class: "d-inline-block align-text-top text-light h3 text-decoration-none" %>


      <div>

        <% if member_signed_in? %>
        <%= link_to  edit_member_registration_path do %>
        <button type="button" class="btn btn-secondary rounded-pill mx-2 "><strong><%= current_member.username %></strong></button>
        <% end %>
        <%= link_to  destroy_member_session_path, method: :delete do %>
        <button type="button" class="btn btn-outline-secondary rounded-pill mx-2">log Out</button>
        <% end %>
        <% else %>
        <%= link_to  new_member_session_path do %>
        <button type="button" class="btn btn-outline-secondary rounded-pill mx-2">log in</button>
        <% end %>
        <%= link_to  new_member_registration_path, class: "button is-primary" do %>
        <button type="button" class="btn btn-secondary rounded-pill mx-2 ">Sign up</button>
        <% end %>
        <% end %>
      </div>


    </div>
  </nav>
  <%= yield %>
</body>

</html>

app/views/posts/_feed.html.erb
<section class="section col-8">

  <% if member_signed_in? %>
  <div class="card rounded shadow-sm border-1 border-light bg-dark mb-2">
    <div class="card-body p-4">
      <div class="container">
        <%= render 'form' %>
      </div>
    </div>
  </div>
  <% end %>

  <% @posts.each do |post| %>

  <div class="card rounded shadow-sm border-1 border-light bg-dark mb-2">
    <div class="card-body p-4">
      <div class="container">
        <h5> <a href="#" class="text-light"><%= post.title %></a></h5>
        <p class="small text-muted font-italic"> <%= post.body %></p>
        <% if member_signed_in? %>
        <p class="smaller text-muted font-italic"><%= post.member.username %></p>
        <% end %>
      </div>
    </div>
  </div>

  <% end %>
</section>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
<%= f.error_notification %>
<%= f.input :title,
             label: "Title",
             input_html: { class: "string my-2"},
             wrapper: false,
             label_html: { class: "label text-white" },
             placeholder: "Enter post title..." %>
<%= f.input :body,
             label: "Post",
             input_html: { class: "textarea my-2"},
             wrapper: false,
             label_html: { class: "label text-white" },
             placeholder: "Compose a new post..." %>



<%= f.button :submit,  class: "btn btn-secondary rounded-pill mx-2 " %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row py-4">
    <%= render "feed" %>
  </div>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>